config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/show/:id' => 'topics#show', as: :topics_show
  post 'topics/create' => 'topics#create'
  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete

  post 'posts/create' => 'posts#create', as: :post_create
  delete 'posts/delete/:id' => 'posts#delete', as: :post_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  validates :name,presence: true
  validates :body,presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
validates :title,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def create
        @post = Post.new(params[:post].permit(:topic_id, :name, :body))
        @post.save
        redirect_to topics_show_path(params[:post]['topic_id'])
    end

    def delete
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to topics_index_path
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @newTopic =Topic.new
  end

  def create
    @topic =Topic.new(params[:topic].permit(:title))
    @topic.save
    redirect_to topics_index_path
  end

  def delete
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_index_path
  end

  def show
    @topic = Topic.find(params[:id])
    @newpost = Post.new(:topic_id => params[:id])
    @posts = Post.where(topic_id: params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lupinus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <h1 class="headertitle">Lupinus</h1>
    </header>
    <%= yield %>
   <footer>
      <h1 class="footertitle">＊＊ Lupinus 2020 ＊＊</h1>
    </footer>
  </body>
</html>

app/views/topics/index.html.erb
<div class= "topic_top">
  <div class = "topic_title" ><h1>トピック一覧</h1></div>
    <% @topics.each do |topic| %>
    <div class = "topic_list"><%= link_to topic.title, topics_show_path(topic.id) %></div>
    <div class = "topic_delete"><%= link_to '[削除]', topic_delete_path(topic.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %></div>
    <% end %>
     </div> 
</div> 
<div class="topic_bottom">
  <div class = "topic_title" ><h1>トピック新規投稿</h1></div>
    <div class= "new_topic">
    <%= form_for @newTopic, :url => {:action => 'create'} do |form| %>
    <b>トピックのタイトル</b>
    <br><%= form.text_field :title %>
    <%= form.submit "新規投稿"%>
    <% end %>
    </div>
</div>

app/views/topics/show.html.erb
<h1 class="topic_name"><%= @topic.title %></h1>
<% @posts.each_with_index do |post| %>
  <div class="comment">
    <%= post.id %>. <%= post.name %> : <%= post.body %>
    <%= link_to '[削除]', post_delete_path(post), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
  </div>
<% end %>

<div class = "new_comments">
<h3 class="new_comment">新規書き込み</h3>
    <%= form_for @newpost, :url => post_create_path do |form| %>
      <b class="font">お名前</b>
      <p><%= form.text_field :name %></p>
      <b class="font">コメント</b>
      <p class="text_area"><%= form.text_area :body %></p>
      <%= form.hidden_field :topic_id %>
      <%= form.submit "コメントする" %>
    <% end %>
</div>